language: node_js
node_js:
  - "7"

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker-cache/

env:
  global:
    - COMPONENT=agile-sqlparser
    - DOCKER_CACHE_FILE=/home/travis/docker-cache/cache.tar.gz
  matrix:
    - DOCKER_IMAGE=agileiot/$COMPONENT-x86_64
      VERSIONIST=true
      BASEIMAGE_BUILD=agileiot/intel-nuc-zulujdk:8-jdk-maven
      BASEIMAGE_DEPLOY=agileiot/intel-nuc-zulujdk:8-jre

before_install:
  - source <(curl -s https://raw.githubusercontent.com/Agile-IoT/agile-ci-scripts/master/agile-ci-functions.sh)
  - docker_upgrade
  - cache_load
  - bootstrap
  - echo "Tagging the build with tag - $DOCKER_TAG"

script:
  - docker_build_if_needed
  - cache_save

after_success:
  - docker_push_if_needed
  - versionist_if_needed
